In [ ]:
# Generally, there are two important things we need to do with data: 
# (i) acquire them; and (ii) process them once they are inside the computer. 

In [ ]:
# Introduce the 𝑛-dimensional array (ndarray), MXNet’s primary tool for storing and transforming data. 
# In MXNet, ndarray is a class and we call any instance “an ndarray”.
# We designed MXNet’s ndarray to be an extension to NumPy’s ndarray with a few killer features.

In [ ]:
# First, MXNet’s ndarray supports asynchronous computation on CPU, GPU, and distributed cloud architectures, 
# whereas NumPy only supports CPU computation. 
# Second, MXNet’s ndarray supports automatic differentiation.

In [1]:
# import the np (numpy) and npx (numpy_extension) modules from MXNet
from mxnet import np, npx
# set_np() function is for compatibility of ndarray processing by other components of MXNet
npx.set_np()

In [2]:
# use arange() to create a row vector x containing the first 12 integers starting with 0, they're created as floats by default
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
# access an ndarray’s shape (the length along each axis)
x.shape

(12,)

In [4]:
# If we want to know the total number of elements in an ndarray, i.e., the product of all of the shape elements
x.size

12

In [5]:
# To change the shape of an ndarray without altering either the number of elements or their values, 
# we can invoke the reshape function
# transform our ndarray x, from a row vector with shape (12,) to a matrix with shape(3, 4). 
x = x.reshape(3, 4)
x
# ndarray can automatically work out one dimension given the rest. 
# We invoke this capability by placing -1 for the dimension that we would like ndarray to automatically infer.
# we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
# The empty method grabs a chunk of memory and hands us back a matrix 
# without bothering to change the value of any of its entries
np.empty((3, 4))

array([[ 0.000000e+00, -2.524355e-29,  0.000000e+00, -2.524355e-29],
       [ 4.203895e-45,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  2.755065e-40]])

In [8]:
# create an ndarray representing a tensor with all elements set to 0 and a shape of (2, 3, 4) 
# tensor: array with more than two axes
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
# create tensors with each element set to 1
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

When we construct arrays to serve as parameters in a neural network, we will typically inititialize their values randomly. 

In [10]:
# creates an ndarray with shape (3, 4), each of its elements is randomly sampled 
# from a standard Gaussian distribution with a mean of 0 and a standard deviation of 1.
np.random.normal(0, 1, size=(3, 4))

array([[ 1.1630787 ,  2.2122064 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.5580711 , -1.2347414 ]])

In [11]:
# specify the exact values for each element in the desired ndarray
# the outermost list corresponds to axis 0, and the inner list to axis 1
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

### Operations

In [12]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [13]:
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

In [14]:
# concatenate multiple ndarrays together, stacking them end-to-end to form a larger ndarray
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# concatenate two matrices along rows (axis 0 , the first element of the shape) 
# vs. columns (axis 1 ,the second element of the shape)
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# construct a binary ndarray via logical statements
x == y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [16]:
# Summing all the elements in the ndarray yields an ndarray with only one element
x.sum()

array(66.)

### Broadcasting Mechanism

In [17]:
# Under certain conditions, even when shapes differ, 
# we can still perform elementwise operations by invoking the broadcasting mechanism. 
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0.],
        [1.],
        [2.]]), array([[0., 1.]]))

In [18]:
# a and b are 3×1 and 1×2 matrices respectively, broadcast the entries of both matrices into a larger 3×2 matrix 
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

### Indexing and Slicing

In [19]:
# access elements according to their relative position to the end of the list by using negative indices
# [-1] selects the last element and [1:3] selects the second and the third elements 
x[-1], x[1:3]

(array([ 8.,  9., 10., 11.]), array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [20]:
# write elements of a matrix by specifying indices
x[1, 2] = 9
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
# assign multiple elements the same value, we simply index all of them and then assign them the value
x[0:2, :] = 12
x

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

### Saving memory

In [22]:
# Python’s id() function, which gives us the exact address of the referenced object in memory.
before = id(y)
y = y + x
id(y) == before # id(y) points to a different location

False

In [23]:
# We can assign the result of an operation to a previously allocated array with slice notation, 
# e.g., y[:] = <expression>. 
z = np.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 4428356176
id(z): 4428356176


In [24]:
# use x[:] = x + y or x += y to reduce the memory overhead of the operation
before = id(x)
x += y
id(x) == before

True

In [25]:
# Converting an MXNet ndarray to a NumPy ndarray, or vice versa, is easy
a = x.asnumpy()
b = np.array(a)
type(a), type(b)

(numpy.ndarray, mxnet.numpy.ndarray)

In [26]:
# convert a size-1 ndarray to a Python scalar
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

### Summary
MXNet’s ndarray is an extension to NumPy’s ndarray with a few killer advantages that make it suitable for deep learning.